language: node_js
sudo: false
node_js:
  - '8'
cache:
  directories:
    - node_modules
script:
  - 'npm run build:ci'
deploy:
  skip_cleanup: true
  provider: script
  script:
    - 'npm run deploy:ci'
  'on':
    tags: true
